# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BathCreator
                                 A QGIS plugin
 Helps to create CE-QUAL-W2 Bathymetric file 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-02-04
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Yoav Bornstein
        email                : yoavborenst@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import csv

from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .create_bathymetry_dialog import BathCreatorDialog
import os.path

#from qgis.core import QgsProject
from qgis.core import (QgsMessageLog, QgsDistanceArea)
from qgis.utils import iface


class BathCreator:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'BathCreator_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&CE-QUAL-W2_Bathymetry ')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('BathCreator', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/create_bathymetry/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'CE-QUAL-W2 Bathymetry '),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&CE-QUAL-W2_Bathymetry '),
                action)
            self.iface.removeToolBarIcon(action)

    def _calculateAangle(self, feature):
        """Calculates the angle in radians between the start and end point of the vector line"""
        multilinestring = feature.geometry().constGet()
        first_part = multilinestring.geometryN(0)
        first_vertex = first_part.pointN(0)
        last_vertex = first_part.pointN(first_part.numPoints()-1)
        az = first_vertex.azimuth(last_vertex)
        if az < 0:
            az = 360 + az
        pi=22/7
        rad = round(az*(pi/180),2)
        return rad

    def _writeExcel(self, data):
        sorted_data = sorted(data, key=lambda k: k['segment'])
        segments = [x['segment'] for x in sorted_data]
        segments.insert(0,'')
        dlx = [x['DLX'] for x in sorted_data]
        dlx.insert(0,'DLX')
        elws = [x['ELWS'] for x in sorted_data]
        elws.insert(0,'ELWS')
        phi = [x['PHI0'] for x in sorted_data]
        phi.insert(0,'PHI0')
        fric = [x['FRIC'] for x in sorted_data]
        fric.insert(0,'FRIC')
        l = ['LAYERH']
        for i in sorted_data:
            l.append('')
        l.append('K')
        l.append('ELEV')
        with open('/home/yoav/out.csv', 'w') as csvfile:
                f = csv.writer(csvfile, delimiter=',')
                f.writerow(["$"])
                f.writerow(segments)
                f.writerow(dlx)
                f.writerow(elws)
                f.writerow(phi)
                f.writerow(fric)
                f.writerow(l)
                

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = BathCreatorDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            layer = iface.activeLayer()
            features = layer.getFeatures()
            d = QgsDistanceArea()
            data = []
            for feat in features:
                data_dic = {}
                
                # Read fields from the vector line
                data_dic['segment']=feat["Segment"]
                data_dic['ELWS']=feat["ELWS"]
                data_dic['FRIC']=feat["FRIC"]
                
                # Get vector line length
                data_dic['DLX']=round(d.measureLength(feat.geometry()),2)
                
                # Calculate line angle
                data_dic['PHI0'] = self._calculateAangle(feat)
                
                QgsMessageLog.logMessage( str(data_dic), tag="Yoav")
                data.append(data_dic)
            self._writeExcel(data)

